-- New Table: WRITERS
CREATE TABLE WRITERS
(
    WRITER_ID INT PRIMARY KEY,
    WRITER_NAME VARCHAR(MAX),
    NATIONALITY VARCHAR(MAX)
);

-- New Table: PUBLICATIONS
CREATE TABLE PUBLICATIONS
(
    PUB_ID INT PRIMARY KEY,
    PUB_TITLE VARCHAR(MAX),
    WRITER_REF INT,
    FOREIGN KEY (WRITER_REF) REFERENCES WRITERS(WRITER_ID)
);

-- Inserting data into WRITERS
INSERT INTO WRITERS (WRITER_ID, WRITER_NAME, NATIONALITY) VALUES
(1, 'Leo Tolstoy', 'Russia'),
(2, 'Gabriel Garcia Marquez', 'Colombia'),
(3, 'Jane Austen', 'England');

-- Inserting data into PUBLICATIONS
INSERT INTO PUBLICATIONS (PUB_ID, PUB_TITLE, WRITER_REF) VALUES
(201, 'War and Peace', 1),
(202, 'One Hundred Years of Solitude', 2),
(203, 'Pride and Prejudice', 3);

-- Joining and selecting
SELECT P.PUB_TITLE AS 'BOOK TITLE', W.WRITER_NAME, W.NATIONALITY
FROM PUBLICATIONS AS P
INNER JOIN WRITERS AS W
ON P.WRITER_REF = W.WRITER_ID;
